// ---------------------------------------------------------------------------
// CENTRAL IMAGE REGISTRY
// ---------------------------------------------------------------------------
// Every <Image> on the site resolves its src through this file. Nothing else
// hardcodes an image path.
//
// Entries are a MIX. Anything whose note says "Real job photo" is the company's
// own photography, imported from human/ by scripts/import-job-photos.mjs. The
// rest is still Pexels stock, pulled by `scripts/fetch-photos.mjs` (see
// public/photos/ATTRIBUTION.md for credits).
//
// ⚠ Stock photos are other people's work. They are a stand-in so the site reads
// as finished — they are NOT a portfolio. Replace the remaining ones with real
// Bulldog job photos before this is presented as the company's own work. The
// `note` on each stock entry describes the shot to take.
//
// To swap one in: drop the photo in /public/photos/, change the `src` here.
// Nothing else on the site needs to be touched.

export type MediaEntry = {
  src: string;
  alt: string;
  note: string;
};

const P = (name: string) => `/photos/${name}.jpg`;

export const media = {
  // ---- Brand ----
  // Real logo. Source artwork is "painters logo final.png" at the repo root;
  // this is the web-sized copy. If the logo is ever revised, regenerate this
  // AND app/icon.png AND app/apple-icon.png from the new source — the icons are
  // head-only crops because the full badge is unreadable at 32px.
  logo: {
    src: '/logo.png',
    alt: 'Bulldog Painters',
    note: 'Supplied brand lockup, reading BULLDOG PAINTERS. Must stay in step with site.name — the header shows both.',
  },

  // Brand mascot illustration. The supplied artwork sits on a solid white
  // backdrop, so it is run through scripts/cutout-mascot.mjs to get real
  // transparency — that is what lets it sit on a dark section. Source is
  // mascot.png at the repo root; re-run the script if the art is redrawn.
  mascot: {
    src: '/photos/mascot.png',
    alt: 'The Bulldog Painters mascot — a bulldog in work coveralls holding a paint brush beside an open can',
    note: 'Supplied brand illustration, background cut out. Keep — do not replace with stock.',
  },

  // Header band texture. Referenced from globals.css (.hdr-band), not through
  // <Photo>, because it is a CSS background — but it is registered here so the
  // slot is visible alongside every other image on the site.
  headerBg: {
    src: P('header-bg'),
    alt: '',
    note: 'Wide brushed-paint texture, ~2400x340. Must be evenly toned — white nav text sits on it.',
  },

  // ---- Home ----
  // Real job photography for the wipe slider in BeforeAfterFeature.
  //
  // Generated by `node scripts/align-showcase.mjs` from bb2.png (before) and
  // bb1.png (after) at the repo root — note that mapping, it is the reverse of
  // what the filenames imply and the script explains why.
  //
  // The sources are aligned by hand but were shot at slightly different
  // distances, leaving a ~8.4% vertical scale difference that no offset can fix.
  // The script measures and corrects it, which is why the output is 560x490
  // rather than the sources' 571x498.
  //
  // The one hard rule is that both frames stay the SAME pixel size as each
  // other. The slider box does not have to match their aspect ratio: an
  // off-ratio box crops both frames identically, which costs a little scene at
  // the edges but keeps them aligned. It is a mismatch BETWEEN the two files
  // that would break the wipe, and the script fails rather than allow that.
  showcaseBefore: {
    src: P('showcase-before'),
    alt: 'A house exterior before painting — olive-stained board siding with bare wood trim around the patio door',
    note: 'Supplied job photo — keep. Must match showcaseAfter dimensions exactly.',
  },
  showcaseAfter: {
    src: P('showcase-after'),
    alt: 'The same house exterior after painting — charcoal siding with white trim around the patio door',
    note: 'Supplied job photo — keep. Must match showcaseBefore dimensions exactly.',
  },
  // Real branded photograph, not stock. Source is "human/client 2.png" at the
  // repo root; this is the optimised copy. Deliberately NOT named home-hero so
  // scripts/fetch-photos.mjs can never overwrite it with a stock image.
  //
  // LANDSCAPE 1400x932 (1.502). The previous hero was portrait, and the hero
  // boxes in app/page.tsx carry the photo's own ratio so nothing is cropped —
  // if this is replaced again at a different shape, those aspect classes and
  // the desktop column widths have to change with it.
  homeHero: {
    src: P('hero-client'),
    alt: 'A Bulldog Painters estimator going through the scope with a homeowner in her entryway',
    note: 'Supplied brand photography — keep. Do not replace with stock.',
  },
  crew: {
    src: P('crew-team'),
    alt: 'The full Bulldog Painters crew photographed together',
    note: 'Real crew photo — keep. Source is human/group painters.png.',
  },
  // A real OpenStreetMap-derived map of the region, not a city photo — the
  // slot used to hold a stock Cincinnati skyline while claiming to be a map.
  // .webp and square (768x768), so it does not go through the P() jpg helper.
  // Wherever it is shown, the OSM attribution must be shown with it.
  serviceAreaMap: {
    src: '/photos/service-area-map.webp',
    alt: 'Map of the Greater Cincinnati region covering southwest Ohio, Northern Kentucky and southeastern Indiana',
    note: 'Real map — keep. Requires \"Map data (c) OpenStreetMap contributors\" wherever displayed.',
  },
  processHero: {
    src: P('process-hero'),
    alt: 'Floors papered and furniture wrapped before painting begins',
    note: 'Landscape 3:2. A prepped room — masked trim, papered floor, wrapped furniture. No people.',
  },

  // ---- Service heroes ----
  interior: {
    src: P('job-interior'),
    alt: 'A Bulldog Painters painter rolling a finish coat onto an interior wall, floors covered',
    note: 'Real job photo — keep. Source is human/interior.png.',
  },
  exterior: {
    src: P('job-exterior'),
    alt: 'A Bulldog Painters painter on a ladder cutting in fresh paint on a home exterior',
    note: 'Real job photo — keep. Source is human/exterior.png. Portrait, so 4:3 cards crop it.',
  },
  cabinets: {
    src: P('job-cabinets'),
    alt: 'A Bulldog Painters painter refinishing kitchen cabinet doors and frames',
    note: 'Real job photo — keep. Source is human/kitchen cabinet.png.',
  },
  commercial: {
    src: P('commercial-painting'),
    alt: 'A commercial office corridor being repainted after hours',
    note: 'Landscape 3:2. Office or retail interior mid-repaint, lift or ladder visible.',
  },
  trimDoors: {
    src: P('trim-and-door-painting'),
    alt: 'Hand-brushed interior trim and a painted six-panel door',
    note: 'Detail shot 4:3. Crisp trim line where wall meets baseboard.',
  },
  ceilings: {
    src: P('ceiling-painting'),
    alt: 'A freshly sprayed flat white ceiling',
    note: 'Upward 4:3 shot of a finished ceiling with a clean wall junction.',
  },
  popcorn: {
    src: P('job-popcorn'),
    alt: 'A Bulldog Painters painter working overhead on a textured ceiling',
    note: 'Real job photo — keep. Source is human/popcorn ceiling.png. Portrait, so 4:3 cards crop it.',
  },
  drywall: {
    src: P('job-drywall'),
    alt: 'A Bulldog Painters crew member feathering compound over drywall patches',
    note: 'Real job photo — keep. Source is human/drywall.jpg.',
  },
  wallpaper: {
    src: P('wallpaper-removal'),
    alt: 'Wallpaper being steamed and stripped from a dining room wall',
    note: 'Wall half-stripped, steamer visible.',
  },
  basement: {
    src: P('basement-painting'),
    alt: 'A finished basement with painted walls and a coated floor',
    note: 'Wide 3:2 of a finished basement, warm lighting.',
  },
  brick: {
    src: P('brick-painting'),
    alt: 'A brick home painted in a warm limewash tone',
    note: 'Elevation shot of painted or limewashed brick.',
  },
  deck: {
    src: P('deck-staining'),
    alt: 'A cedar deck freshly stained and sealed',
    note: 'Low-angle 3:2 along the deck boards, wet-look finish.',
  },
  fence: {
    src: P('fence-painting'),
    alt: 'A stained privacy fence running along a back yard',
    note: 'Fence line receding into frame, 16:9.',
  },
  epoxy: {
    src: P('job-floor-coating'),
    alt: 'A Bulldog Painters painter applying a flake floor coating',
    note: 'Real job photo — keep. Source is human/basement.png.',
  },
  pressureWash: {
    src: P('pressure-washing'),
    alt: 'Siding being pressure washed before painting',
    note: 'Action shot, clean stripe visible against dirty siding.',
  },
} as const satisfies Record<string, MediaEntry>;

export type MediaKey = keyof typeof media;

// ---- Project gallery ----
// Nine before/after pairs. Replace both paths per pair with real job photos.
export const galleryPairs = Array.from({ length: 9 }, (_, i) => ({
  before: P(`ba-${i + 1}-before`),
  after: P(`ba-${i + 1}-after`),
}));
